application: authtopus
version: 2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
# Endpoints handler
- url: /_ah/api/.*
  script: main.API
# Cron handlers
- url: /cron/.*
  script: main.CRON
  login: admin
# App handlers
- url: (.*)/(|login|register|user/verify|user/edit/.*|password-reset|set-password|social-login-password)
  secure: always
  static_files: webapp\1/index.html
  upload: webapp
- url: (.*)
  static_files: webapp\1
  upload: webapp

libraries:
- name: pycrypto
  version: latest
- name: webapp2
  version: 2.5.2
- name: ssl
  version: latest

